// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package protobuf;

public final class MessagePB {
  private MessagePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
     */
    boolean hasType();
    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
     */
    protobuf.MessagePB.Message.MessageType getType();

    /**
     * <code>optional string mess = 2;</code>
     */
    boolean hasMess();
    /**
     * <code>optional string mess = 2;</code>
     */
    java.lang.String getMess();
    /**
     * <code>optional string mess = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessBytes();
  }
  /**
   * Protobuf type {@code protobuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 5;
      mess_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protobuf.MessagePB.Message.MessageType value = protobuf.MessagePB.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              mess_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MessagePB.internal_static_protobuf_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MessagePB.internal_static_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MessagePB.Message.class, protobuf.MessagePB.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * NONE
       * </pre>
       *
       * <code>Z = 0;</code>
       */
      Z(0),
      /**
       * <pre>
       * VIEW_SCREEN
       * </pre>
       *
       * <code>V = 1;</code>
       */
      V(1),
      /**
       * <pre>
       * SEND_FILE
       * </pre>
       *
       * <code>F = 2;</code>
       */
      F(2),
      /**
       * <pre>
       * CHAT
       * </pre>
       *
       * <code>C = 3;</code>
       */
      C(3),
      /**
       * <pre>
       * YES
       * </pre>
       *
       * <code>Y = 4;</code>
       */
      Y(4),
      /**
       * <pre>
       * NO
       * </pre>
       *
       * <code>N = 5;</code>
       */
      N(5),
      /**
       * <pre>
       * REQUEST_VIEW_SCREEN
       * </pre>
       *
       * <code>RV = 6;</code>
       */
      RV(6),
      /**
       * <pre>
       *REQUEST_SEND_FILE
       * </pre>
       *
       * <code>RF = 7;</code>
       */
      RF(7),
      /**
       * <pre>
       * REQUEST_CHAT
       * </pre>
       *
       * <code>RC = 8;</code>
       */
      RC(8),
      /**
       * <pre>
       * ACCEPT
       * </pre>
       *
       * <code>A = 9;</code>
       */
      A(9),
      /**
       * <pre>
       * REJECT
       * </pre>
       *
       * <code>R = 10;</code>
       */
      R(10),
      /**
       * <pre>
       * NEXT
       * </pre>
       *
       * <code>T = 11;</code>
       */
      T(11),
      /**
       * <pre>
       * ERROR
       * </pre>
       *
       * <code>E = 12;</code>
       */
      E(12),
      ;

      /**
       * <pre>
       * NONE
       * </pre>
       *
       * <code>Z = 0;</code>
       */
      public static final int Z_VALUE = 0;
      /**
       * <pre>
       * VIEW_SCREEN
       * </pre>
       *
       * <code>V = 1;</code>
       */
      public static final int V_VALUE = 1;
      /**
       * <pre>
       * SEND_FILE
       * </pre>
       *
       * <code>F = 2;</code>
       */
      public static final int F_VALUE = 2;
      /**
       * <pre>
       * CHAT
       * </pre>
       *
       * <code>C = 3;</code>
       */
      public static final int C_VALUE = 3;
      /**
       * <pre>
       * YES
       * </pre>
       *
       * <code>Y = 4;</code>
       */
      public static final int Y_VALUE = 4;
      /**
       * <pre>
       * NO
       * </pre>
       *
       * <code>N = 5;</code>
       */
      public static final int N_VALUE = 5;
      /**
       * <pre>
       * REQUEST_VIEW_SCREEN
       * </pre>
       *
       * <code>RV = 6;</code>
       */
      public static final int RV_VALUE = 6;
      /**
       * <pre>
       *REQUEST_SEND_FILE
       * </pre>
       *
       * <code>RF = 7;</code>
       */
      public static final int RF_VALUE = 7;
      /**
       * <pre>
       * REQUEST_CHAT
       * </pre>
       *
       * <code>RC = 8;</code>
       */
      public static final int RC_VALUE = 8;
      /**
       * <pre>
       * ACCEPT
       * </pre>
       *
       * <code>A = 9;</code>
       */
      public static final int A_VALUE = 9;
      /**
       * <pre>
       * REJECT
       * </pre>
       *
       * <code>R = 10;</code>
       */
      public static final int R_VALUE = 10;
      /**
       * <pre>
       * NEXT
       * </pre>
       *
       * <code>T = 11;</code>
       */
      public static final int T_VALUE = 11;
      /**
       * <pre>
       * ERROR
       * </pre>
       *
       * <code>E = 12;</code>
       */
      public static final int E_VALUE = 12;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return Z;
          case 1: return V;
          case 2: return F;
          case 3: return C;
          case 4: return Y;
          case 5: return N;
          case 6: return RV;
          case 7: return RF;
          case 8: return RC;
          case 9: return A;
          case 10: return R;
          case 11: return T;
          case 12: return E;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.MessagePB.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Message.MessageType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
     */
    public protobuf.MessagePB.Message.MessageType getType() {
      @SuppressWarnings("deprecation")
      protobuf.MessagePB.Message.MessageType result = protobuf.MessagePB.Message.MessageType.valueOf(type_);
      return result == null ? protobuf.MessagePB.Message.MessageType.N : result;
    }

    public static final int MESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object mess_;
    /**
     * <code>optional string mess = 2;</code>
     */
    public boolean hasMess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string mess = 2;</code>
     */
    public java.lang.String getMess() {
      java.lang.Object ref = mess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mess_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mess = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessBytes() {
      java.lang.Object ref = mess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mess_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mess_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.MessagePB.Message)) {
        return super.equals(obj);
      }
      protobuf.MessagePB.Message other = (protobuf.MessagePB.Message) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasMess() == other.hasMess());
      if (hasMess()) {
        result = result && getMess()
            .equals(other.getMess());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasMess()) {
        hash = (37 * hash) + MESS_FIELD_NUMBER;
        hash = (53 * hash) + getMess().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.MessagePB.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MessagePB.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MessagePB.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MessagePB.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MessagePB.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MessagePB.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MessagePB.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.MessagePB.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.MessagePB.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.MessagePB.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.MessagePB.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.MessagePB.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.MessagePB.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Message)
        protobuf.MessagePB.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MessagePB.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MessagePB.internal_static_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MessagePB.Message.class, protobuf.MessagePB.Message.Builder.class);
      }

      // Construct using protobuf.MessagePB.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 5;
        bitField0_ = (bitField0_ & ~0x00000001);
        mess_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MessagePB.internal_static_protobuf_Message_descriptor;
      }

      @java.lang.Override
      public protobuf.MessagePB.Message getDefaultInstanceForType() {
        return protobuf.MessagePB.Message.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.MessagePB.Message build() {
        protobuf.MessagePB.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.MessagePB.Message buildPartial() {
        protobuf.MessagePB.Message result = new protobuf.MessagePB.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mess_ = mess_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MessagePB.Message) {
          return mergeFrom((protobuf.MessagePB.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MessagePB.Message other) {
        if (other == protobuf.MessagePB.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMess()) {
          bitField0_ |= 0x00000002;
          mess_ = other.mess_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MessagePB.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MessagePB.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 5;
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
       */
      public protobuf.MessagePB.Message.MessageType getType() {
        @SuppressWarnings("deprecation")
        protobuf.MessagePB.Message.MessageType result = protobuf.MessagePB.Message.MessageType.valueOf(type_);
        return result == null ? protobuf.MessagePB.Message.MessageType.N : result;
      }
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
       */
      public Builder setType(protobuf.MessagePB.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.Message.MessageType type = 1 [default = N];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 5;
        onChanged();
        return this;
      }

      private java.lang.Object mess_ = "";
      /**
       * <code>optional string mess = 2;</code>
       */
      public boolean hasMess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string mess = 2;</code>
       */
      public java.lang.String getMess() {
        java.lang.Object ref = mess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mess_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mess = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessBytes() {
        java.lang.Object ref = mess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mess = 2;</code>
       */
      public Builder setMess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mess = 2;</code>
       */
      public Builder clearMess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mess_ = getDefaultInstance().getMess();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mess = 2;</code>
       */
      public Builder setMessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mess_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Message)
    private static final protobuf.MessagePB.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.MessagePB.Message();
    }

    public static protobuf.MessagePB.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.MessagePB.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SegmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Segment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 1;</code>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>required string receiver = 2;</code>
     */
    boolean hasReceiver();
    /**
     * <code>required string receiver = 2;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>required string receiver = 2;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>required string data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>required string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required string dchecksum = 4;</code>
     */
    boolean hasDchecksum();
    /**
     * <code>required string dchecksum = 4;</code>
     */
    java.lang.String getDchecksum();
    /**
     * <code>required string dchecksum = 4;</code>
     */
    com.google.protobuf.ByteString
        getDchecksumBytes();

    /**
     * <code>required string signature = 5;</code>
     */
    boolean hasSignature();
    /**
     * <code>required string signature = 5;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>required string signature = 5;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>required string schecksum = 6;</code>
     */
    boolean hasSchecksum();
    /**
     * <code>required string schecksum = 6;</code>
     */
    java.lang.String getSchecksum();
    /**
     * <code>required string schecksum = 6;</code>
     */
    com.google.protobuf.ByteString
        getSchecksumBytes();

    /**
     * <code>required .protobuf.Segment.SegmentType type = 7;</code>
     */
    boolean hasType();
    /**
     * <code>required .protobuf.Segment.SegmentType type = 7;</code>
     */
    protobuf.MessagePB.Segment.SegmentType getType();

    /**
     * <code>optional string pubkey = 8;</code>
     */
    boolean hasPubkey();
    /**
     * <code>optional string pubkey = 8;</code>
     */
    java.lang.String getPubkey();
    /**
     * <code>optional string pubkey = 8;</code>
     */
    com.google.protobuf.ByteString
        getPubkeyBytes();

    /**
     * <code>optional string verkey = 9;</code>
     */
    boolean hasVerkey();
    /**
     * <code>optional string verkey = 9;</code>
     */
    java.lang.String getVerkey();
    /**
     * <code>optional string verkey = 9;</code>
     */
    com.google.protobuf.ByteString
        getVerkeyBytes();
  }
  /**
   * Protobuf type {@code protobuf.Segment}
   */
  public  static final class Segment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Segment)
      SegmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Segment.newBuilder() to construct.
    private Segment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Segment() {
      sender_ = "";
      receiver_ = "";
      data_ = "";
      dchecksum_ = "";
      signature_ = "";
      schecksum_ = "";
      type_ = 0;
      pubkey_ = "";
      verkey_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Segment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sender_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              receiver_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              data_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dchecksum_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              signature_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              schecksum_ = bs;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protobuf.MessagePB.Segment.SegmentType value = protobuf.MessagePB.Segment.SegmentType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                type_ = rawValue;
              }
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              pubkey_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              verkey_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MessagePB.internal_static_protobuf_Segment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MessagePB.internal_static_protobuf_Segment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.MessagePB.Segment.class, protobuf.MessagePB.Segment.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Segment.SegmentType}
     */
    public enum SegmentType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>REQUEST_CONNECT = 1;</code>
       */
      REQUEST_CONNECT(1),
      /**
       * <code>REQUEST_DISCONNECT = 2;</code>
       */
      REQUEST_DISCONNECT(2),
      /**
       * <code>SEND_KEY = 3;</code>
       */
      SEND_KEY(3),
      /**
       * <code>REQUEST_KEY = 4;</code>
       */
      REQUEST_KEY(4),
      /**
       * <code>ACCEPT_CONNECT = 5;</code>
       */
      ACCEPT_CONNECT(5),
      /**
       * <code>REJECT_CONNECT = 6;</code>
       */
      REJECT_CONNECT(6),
      /**
       * <code>NEXT = 7;</code>
       */
      NEXT(7),
      /**
       * <code>ERROR = 8;</code>
       */
      ERROR(8),
      /**
       * <code>REQUEST_CHAT = 9;</code>
       */
      REQUEST_CHAT(9),
      /**
       * <code>REQUEST_SEND_FILE = 10;</code>
       */
      REQUEST_SEND_FILE(10),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>REQUEST_CONNECT = 1;</code>
       */
      public static final int REQUEST_CONNECT_VALUE = 1;
      /**
       * <code>REQUEST_DISCONNECT = 2;</code>
       */
      public static final int REQUEST_DISCONNECT_VALUE = 2;
      /**
       * <code>SEND_KEY = 3;</code>
       */
      public static final int SEND_KEY_VALUE = 3;
      /**
       * <code>REQUEST_KEY = 4;</code>
       */
      public static final int REQUEST_KEY_VALUE = 4;
      /**
       * <code>ACCEPT_CONNECT = 5;</code>
       */
      public static final int ACCEPT_CONNECT_VALUE = 5;
      /**
       * <code>REJECT_CONNECT = 6;</code>
       */
      public static final int REJECT_CONNECT_VALUE = 6;
      /**
       * <code>NEXT = 7;</code>
       */
      public static final int NEXT_VALUE = 7;
      /**
       * <code>ERROR = 8;</code>
       */
      public static final int ERROR_VALUE = 8;
      /**
       * <code>REQUEST_CHAT = 9;</code>
       */
      public static final int REQUEST_CHAT_VALUE = 9;
      /**
       * <code>REQUEST_SEND_FILE = 10;</code>
       */
      public static final int REQUEST_SEND_FILE_VALUE = 10;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SegmentType valueOf(int value) {
        return forNumber(value);
      }

      public static SegmentType forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return REQUEST_CONNECT;
          case 2: return REQUEST_DISCONNECT;
          case 3: return SEND_KEY;
          case 4: return REQUEST_KEY;
          case 5: return ACCEPT_CONNECT;
          case 6: return REJECT_CONNECT;
          case 7: return NEXT;
          case 8: return ERROR;
          case 9: return REQUEST_CHAT;
          case 10: return REQUEST_SEND_FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SegmentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SegmentType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SegmentType>() {
              public SegmentType findValueByNumber(int number) {
                return SegmentType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.MessagePB.Segment.getDescriptor().getEnumTypes().get(0);
      }

      private static final SegmentType[] VALUES = values();

      public static SegmentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SegmentType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Segment.SegmentType)
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private volatile java.lang.Object sender_;
    /**
     * <code>required string sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 2;
    private volatile java.lang.Object receiver_;
    /**
     * <code>required string receiver = 2;</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string receiver = 2;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiver = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object data_;
    /**
     * <code>required string data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DCHECKSUM_FIELD_NUMBER = 4;
    private volatile java.lang.Object dchecksum_;
    /**
     * <code>required string dchecksum = 4;</code>
     */
    public boolean hasDchecksum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string dchecksum = 4;</code>
     */
    public java.lang.String getDchecksum() {
      java.lang.Object ref = dchecksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dchecksum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dchecksum = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDchecksumBytes() {
      java.lang.Object ref = dchecksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dchecksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 5;
    private volatile java.lang.Object signature_;
    /**
     * <code>required string signature = 5;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string signature = 5;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signature = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHECKSUM_FIELD_NUMBER = 6;
    private volatile java.lang.Object schecksum_;
    /**
     * <code>required string schecksum = 6;</code>
     */
    public boolean hasSchecksum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string schecksum = 6;</code>
     */
    public java.lang.String getSchecksum() {
      java.lang.Object ref = schecksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          schecksum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string schecksum = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSchecksumBytes() {
      java.lang.Object ref = schecksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schecksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <code>required .protobuf.Segment.SegmentType type = 7;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .protobuf.Segment.SegmentType type = 7;</code>
     */
    public protobuf.MessagePB.Segment.SegmentType getType() {
      @SuppressWarnings("deprecation")
      protobuf.MessagePB.Segment.SegmentType result = protobuf.MessagePB.Segment.SegmentType.valueOf(type_);
      return result == null ? protobuf.MessagePB.Segment.SegmentType.NONE : result;
    }

    public static final int PUBKEY_FIELD_NUMBER = 8;
    private volatile java.lang.Object pubkey_;
    /**
     * <code>optional string pubkey = 8;</code>
     */
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string pubkey = 8;</code>
     */
    public java.lang.String getPubkey() {
      java.lang.Object ref = pubkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pubkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pubkey = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPubkeyBytes() {
      java.lang.Object ref = pubkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERKEY_FIELD_NUMBER = 9;
    private volatile java.lang.Object verkey_;
    /**
     * <code>optional string verkey = 9;</code>
     */
    public boolean hasVerkey() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string verkey = 9;</code>
     */
    public java.lang.String getVerkey() {
      java.lang.Object ref = verkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          verkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string verkey = 9;</code>
     */
    public com.google.protobuf.ByteString
        getVerkeyBytes() {
      java.lang.Object ref = verkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiver()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDchecksum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSchecksum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, receiver_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dchecksum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, signature_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, schecksum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, type_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pubkey_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, verkey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, receiver_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dchecksum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, signature_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, schecksum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, type_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pubkey_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, verkey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.MessagePB.Segment)) {
        return super.equals(obj);
      }
      protobuf.MessagePB.Segment other = (protobuf.MessagePB.Segment) obj;

      boolean result = true;
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && (hasReceiver() == other.hasReceiver());
      if (hasReceiver()) {
        result = result && getReceiver()
            .equals(other.getReceiver());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasDchecksum() == other.hasDchecksum());
      if (hasDchecksum()) {
        result = result && getDchecksum()
            .equals(other.getDchecksum());
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (hasSchecksum() == other.hasSchecksum());
      if (hasSchecksum()) {
        result = result && getSchecksum()
            .equals(other.getSchecksum());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasPubkey() == other.hasPubkey());
      if (hasPubkey()) {
        result = result && getPubkey()
            .equals(other.getPubkey());
      }
      result = result && (hasVerkey() == other.hasVerkey());
      if (hasVerkey()) {
        result = result && getVerkey()
            .equals(other.getVerkey());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasDchecksum()) {
        hash = (37 * hash) + DCHECKSUM_FIELD_NUMBER;
        hash = (53 * hash) + getDchecksum().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasSchecksum()) {
        hash = (37 * hash) + SCHECKSUM_FIELD_NUMBER;
        hash = (53 * hash) + getSchecksum().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasPubkey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubkey().hashCode();
      }
      if (hasVerkey()) {
        hash = (37 * hash) + VERKEY_FIELD_NUMBER;
        hash = (53 * hash) + getVerkey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.MessagePB.Segment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MessagePB.Segment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.MessagePB.Segment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.MessagePB.Segment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.MessagePB.Segment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.MessagePB.Segment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.MessagePB.Segment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Segment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Segment)
        protobuf.MessagePB.SegmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MessagePB.internal_static_protobuf_Segment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MessagePB.internal_static_protobuf_Segment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.MessagePB.Segment.class, protobuf.MessagePB.Segment.Builder.class);
      }

      // Construct using protobuf.MessagePB.Segment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        receiver_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dchecksum_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        schecksum_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        pubkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        verkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MessagePB.internal_static_protobuf_Segment_descriptor;
      }

      @java.lang.Override
      public protobuf.MessagePB.Segment getDefaultInstanceForType() {
        return protobuf.MessagePB.Segment.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.MessagePB.Segment build() {
        protobuf.MessagePB.Segment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.MessagePB.Segment buildPartial() {
        protobuf.MessagePB.Segment result = new protobuf.MessagePB.Segment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.receiver_ = receiver_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dchecksum_ = dchecksum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.schecksum_ = schecksum_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pubkey_ = pubkey_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.verkey_ = verkey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MessagePB.Segment) {
          return mergeFrom((protobuf.MessagePB.Segment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.MessagePB.Segment other) {
        if (other == protobuf.MessagePB.Segment.getDefaultInstance()) return this;
        if (other.hasSender()) {
          bitField0_ |= 0x00000001;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasReceiver()) {
          bitField0_ |= 0x00000002;
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000004;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasDchecksum()) {
          bitField0_ |= 0x00000008;
          dchecksum_ = other.dchecksum_;
          onChanged();
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000010;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasSchecksum()) {
          bitField0_ |= 0x00000020;
          schecksum_ = other.schecksum_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPubkey()) {
          bitField0_ |= 0x00000080;
          pubkey_ = other.pubkey_;
          onChanged();
        }
        if (other.hasVerkey()) {
          bitField0_ |= 0x00000100;
          verkey_ = other.verkey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSender()) {
          return false;
        }
        if (!hasReceiver()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        if (!hasDchecksum()) {
          return false;
        }
        if (!hasSignature()) {
          return false;
        }
        if (!hasSchecksum()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.MessagePB.Segment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.MessagePB.Segment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sender_ = "";
      /**
       * <code>required string sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 1;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>required string receiver = 2;</code>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string receiver = 2;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiver = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiver = 2;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiver = 2;</code>
       */
      public Builder clearReceiver() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiver = 2;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dchecksum_ = "";
      /**
       * <code>required string dchecksum = 4;</code>
       */
      public boolean hasDchecksum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string dchecksum = 4;</code>
       */
      public java.lang.String getDchecksum() {
        java.lang.Object ref = dchecksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dchecksum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dchecksum = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDchecksumBytes() {
        java.lang.Object ref = dchecksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dchecksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dchecksum = 4;</code>
       */
      public Builder setDchecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dchecksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dchecksum = 4;</code>
       */
      public Builder clearDchecksum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dchecksum_ = getDefaultInstance().getDchecksum();
        onChanged();
        return this;
      }
      /**
       * <code>required string dchecksum = 4;</code>
       */
      public Builder setDchecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dchecksum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>required string signature = 5;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string signature = 5;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string signature = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signature = 5;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 5;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000010);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 5;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        signature_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object schecksum_ = "";
      /**
       * <code>required string schecksum = 6;</code>
       */
      public boolean hasSchecksum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string schecksum = 6;</code>
       */
      public java.lang.String getSchecksum() {
        java.lang.Object ref = schecksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            schecksum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string schecksum = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSchecksumBytes() {
        java.lang.Object ref = schecksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schecksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string schecksum = 6;</code>
       */
      public Builder setSchecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        schecksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string schecksum = 6;</code>
       */
      public Builder clearSchecksum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        schecksum_ = getDefaultInstance().getSchecksum();
        onChanged();
        return this;
      }
      /**
       * <code>required string schecksum = 6;</code>
       */
      public Builder setSchecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        schecksum_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>required .protobuf.Segment.SegmentType type = 7;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required .protobuf.Segment.SegmentType type = 7;</code>
       */
      public protobuf.MessagePB.Segment.SegmentType getType() {
        @SuppressWarnings("deprecation")
        protobuf.MessagePB.Segment.SegmentType result = protobuf.MessagePB.Segment.SegmentType.valueOf(type_);
        return result == null ? protobuf.MessagePB.Segment.SegmentType.NONE : result;
      }
      /**
       * <code>required .protobuf.Segment.SegmentType type = 7;</code>
       */
      public Builder setType(protobuf.MessagePB.Segment.SegmentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.Segment.SegmentType type = 7;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pubkey_ = "";
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public boolean hasPubkey() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public java.lang.String getPubkey() {
        java.lang.Object ref = pubkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pubkey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPubkeyBytes() {
        java.lang.Object ref = pubkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public Builder setPubkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public Builder clearPubkey() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public Builder setPubkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pubkey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object verkey_ = "";
      /**
       * <code>optional string verkey = 9;</code>
       */
      public boolean hasVerkey() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public java.lang.String getVerkey() {
        java.lang.Object ref = verkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            verkey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public com.google.protobuf.ByteString
          getVerkeyBytes() {
        java.lang.Object ref = verkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          verkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public Builder setVerkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        verkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public Builder clearVerkey() {
        bitField0_ = (bitField0_ & ~0x00000100);
        verkey_ = getDefaultInstance().getVerkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public Builder setVerkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        verkey_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Segment)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Segment)
    private static final protobuf.MessagePB.Segment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.MessagePB.Segment();
    }

    public static protobuf.MessagePB.Segment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Segment>
        PARSER = new com.google.protobuf.AbstractParser<Segment>() {
      @java.lang.Override
      public Segment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Segment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Segment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Segment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.MessagePB.Segment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Segment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Segment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010protobuf\"\264\001\n\007Message\022.\n" +
      "\004type\030\001 \002(\0162\035.protobuf.Message.MessageTy" +
      "pe:\001N\022\014\n\004mess\030\002 \001(\t\"k\n\013MessageType\022\005\n\001Z\020" +
      "\000\022\005\n\001V\020\001\022\005\n\001F\020\002\022\005\n\001C\020\003\022\005\n\001Y\020\004\022\005\n\001N\020\005\022\006\n\002" +
      "RV\020\006\022\006\n\002RF\020\007\022\006\n\002RC\020\010\022\005\n\001A\020\t\022\005\n\001R\020\n\022\005\n\001T\020" +
      "\013\022\005\n\001E\020\014\"\213\003\n\007Segment\022\016\n\006sender\030\001 \002(\t\022\020\n\010" +
      "receiver\030\002 \002(\t\022\014\n\004data\030\003 \002(\t\022\021\n\tdchecksu" +
      "m\030\004 \002(\t\022\021\n\tsignature\030\005 \002(\t\022\021\n\tschecksum\030" +
      "\006 \002(\t\022+\n\004type\030\007 \002(\0162\035.protobuf.Segment.S" +
      "egmentType\022\016\n\006pubkey\030\010 \001(\t\022\016\n\006verkey\030\t \001" +
      "(\t\"\311\001\n\013SegmentType\022\010\n\004NONE\020\000\022\023\n\017REQUEST_" +
      "CONNECT\020\001\022\026\n\022REQUEST_DISCONNECT\020\002\022\014\n\010SEN" +
      "D_KEY\020\003\022\017\n\013REQUEST_KEY\020\004\022\022\n\016ACCEPT_CONNE" +
      "CT\020\005\022\022\n\016REJECT_CONNECT\020\006\022\010\n\004NEXT\020\007\022\t\n\005ER" +
      "ROR\020\010\022\020\n\014REQUEST_CHAT\020\t\022\025\n\021REQUEST_SEND_" +
      "FILE\020\nB\013B\tMessagePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Message_descriptor,
        new java.lang.String[] { "Type", "Mess", });
    internal_static_protobuf_Segment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_Segment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Segment_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Data", "Dchecksum", "Signature", "Schecksum", "Type", "Pubkey", "Verkey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
